version: 0.2 

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:iam::600637289532:role/service-role/codebuild-coursera-week4-aws-flask-cd-codebuild-service-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: coursera-week4-aws-flask-cd-env2
  Timeout: 10   

phases:
  install:
    runtime-versions:
      python: 3.7
      
  pre_build:
    commands:
      - python3.7 -m venv ~/.venv
      - source ~/.venv/bin/activate 
      - make install
      - make lint
      
  build:
    commands:
      - make deploy