branch-defaults:
  main:
    environment: coursera-week4-aws-flask-cd-env2
    group_suffix: null
environment-defaults:
  coursera-week4-aws-flask-cd-env2:
    branch: null
    repository: null
global:
  application_name: coursera-week4-aws-flask-cd
  branch: null
  default_ec2_keyname: courseraweek4clouddev
  default_platform: Python 3.7
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
